# Generated by Django 4.2.11 on 2026-09-18 11:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='Bankname', max_length=200)),
                ('account_number', models.CharField(blank=True, help_text='Kontonummer', max_length=50, null=True)),
                ('iban', models.CharField(blank=True, help_text='IBAN', max_length=34, null=True)),
                ('bic', models.CharField(blank=True, help_text='BIC/SWIFT-Code', max_length=11, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Standard-Bankverbindung')),
                ('account_holder', models.CharField(blank=True, help_text='Kontoinhaber (falls abweichend)', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notizen')),
            ],
            options={
                'verbose_name': 'Bankverbindung',
                'verbose_name_plural': 'Bankverbindungen',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contact_number', models.CharField(help_text='Kundennummer/Lieferantennummer', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Firmenname', max_length=200)),
                ('first_name', models.CharField(blank=True, help_text='Vorname (Ansprechpartner)', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Nachname (Ansprechpartner)', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='E-Mail-Adresse', max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, help_text='Telefonnummer', max_length=30, null=True)),
                ('mobile', models.CharField(blank=True, help_text='Mobiltelefon', max_length=30, null=True)),
                ('fax', models.CharField(blank=True, help_text='Fax', max_length=30, null=True)),
                ('website', models.URLField(blank=True, help_text='Webseite', null=True)),
                ('tax_number', models.CharField(blank=True, help_text='Steuernummer', max_length=50, null=True)),
                ('vat_number', models.CharField(blank=True, help_text='Umsatzsteuer-Identifikationsnummer', max_length=50, null=True, validators=[django.core.validators.RegexValidator(code='invalid_vat_number', message='USt-IdNr. muss dem EU-Format entsprechen (z.B. DE123456789)', regex='^[A-Za-z]{2}[A-Za-z0-9]{8,12}$')])),
                ('address_line_1', models.CharField(blank=True, help_text='Straße und Hausnummer', max_length=200, null=True)),
                ('address_line_2', models.CharField(blank=True, help_text='Adresszusatz', max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postleitzahl', max_length=20, null=True)),
                ('city', models.CharField(blank=True, help_text='Stadt', max_length=100, null=True)),
                ('currency', models.CharField(default='EUR', help_text='Währung', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Aktiv')),
                ('notes', models.TextField(blank=True, help_text='Notizen')),
                ('internal_notes', models.TextField(blank=True, help_text='Interne Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_customer', models.BooleanField(default=False, help_text='Kunde')),
                ('is_supplier', models.BooleanField(default=False, help_text='Lieferant')),
                ('is_both', models.BooleanField(default=False, help_text='Kunde und Lieferant')),
            ],
            options={
                'verbose_name': 'Kontaktart',
                'verbose_name_plural': 'Kontaktarten',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('eu_member', models.BooleanField(default=False, help_text='EU-Mitglied')),
            ],
            options={
                'verbose_name': 'Land',
                'verbose_name_plural': 'Länder',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Branche',
                'verbose_name_plural': 'Branchen',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Vorname', max_length=100)),
                ('last_name', models.CharField(help_text='Nachname', max_length=100)),
                ('position', models.CharField(blank=True, help_text='Position', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='E-Mail-Adresse', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Telefonnummer', max_length=30, null=True)),
                ('mobile', models.CharField(blank=True, help_text='Mobiltelefon', max_length=30, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Hauptansprechpartner')),
                ('notes', models.TextField(blank=True, help_text='Notizen')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Ansprechpartner',
                'verbose_name_plural': 'Ansprechpartner',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(help_text='Kontaktart', on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='contacts.contacttype'),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Land', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.country'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='default_account',
            field=models.ForeignKey(blank=True, help_text='Standardkonto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_as_default', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='contact',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='Branche', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.industry'),
        ),
    ]
