# Generated by Django 4.2.11 on 2026-09-18 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='payment_term',
            field=models.ForeignKey(blank=True, help_text='Standard-Zahlungsbedingung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='invoices.paymentterm'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='contacts.contact'),
        ),
    ]
