# Generated by Django 4.2.11 on 2026-09-18 11:21

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_number', models.CharField(help_text='Rechnungsnummer', max_length=50, unique=True)),
                ('date', models.DateField(help_text='Rechnungsdatum')),
                ('due_date', models.DateField(blank=True, help_text='Fälligkeitsdatum', null=True)),
                ('payment_date', models.DateField(blank=True, help_text='Zahlungsdatum', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Nettobetrag', max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Steuerbetrag', max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Gesamtbetrag', max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Gezahlter Betrag', max_digits=15)),
                ('reference', models.CharField(blank=True, help_text='Referenz (z.B. Bestellnummer)', max_length=200, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Interne Notizen')),
                ('customer_notes', models.TextField(blank=True, help_text='Notizen für den Kunden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, help_text='PDF-Datei', null=True, upload_to='invoices/pdfs/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Kunde/Lieferant', on_delete=django.db.models.deletion.PROTECT, related_name='invoices_as_customer', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_final', models.BooleanField(default=False, help_text='Endgültiger Status')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rechnungsstatus',
                'verbose_name_plural': 'Rechnungsstatus',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_credit_note', models.BooleanField(default=False, help_text='Gutschrift')),
            ],
            options={
                'verbose_name': 'Rechnungstyp',
                'verbose_name_plural': 'Rechnungstypen',
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('days', models.PositiveIntegerField(default=14, help_text='Zahlungsziel in Tagen')),
                ('description', models.TextField(blank=True)),
                ('discount_days', models.PositiveIntegerField(blank=True, default=0, help_text='Tage für Skonto', null=True)),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Skonto in %', max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Zahlungsbedingung',
                'verbose_name_plural': 'Zahlungsbedingungen',
            },
        ),
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Name der Vorlage', max_length=200)),
                ('recurrence_type', models.CharField(choices=[('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('monthly', 'Monatlich'), ('quarterly', 'Quartalsweise'), ('yearly', 'Jährlich')], default='monthly', help_text='Wiederholung', max_length=20)),
                ('recurrence_interval', models.PositiveIntegerField(default=1, help_text='Intervall (z.B. alle 2 Monate)')),
                ('start_date', models.DateField(help_text='Startdatum')),
                ('end_date', models.DateField(blank=True, help_text='Enddatum', null=True)),
                ('next_invoice_date', models.DateField(blank=True, help_text='Nächstes Rechnungsdatum', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Aktiv')),
                ('auto_send', models.BooleanField(default=False, help_text='Automatisch senden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Kunde', on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoices', to='contacts.contact')),
                ('invoice_type', models.ForeignKey(help_text='Rechnungstyp', on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoice_templates', to='invoices.invoicetype')),
                ('payment_term', models.ForeignKey(blank=True, help_text='Zahlungsbedingung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_invoice_templates', to='invoices.paymentterm')),
                ('receivable_account', models.ForeignKey(blank=True, help_text='Forderungskonto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoice_templates_as_receivable', to='accounting.account')),
                ('revenue_account', models.ForeignKey(blank=True, help_text='Ertragskonto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoice_templates_as_revenue', to='accounting.account')),
                ('tax_account', models.ForeignKey(blank=True, help_text='Steuerkonto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoice_templates_as_tax', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Wiederkehrende Rechnung',
                'verbose_name_plural': 'Wiederkehrende Rechnungen',
            },
        ),
        migrations.CreateModel(
            name='RecurringInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(help_text='Beschreibung')),
                ('quantity', models.DecimalField(decimal_places=4, default=1.0, help_text='Menge', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Einzelpreis', max_digits=15)),
                ('cost_center', models.CharField(blank=True, help_text='Kostenstelle', max_length=50, null=True)),
                ('account', models.ForeignKey(blank=True, help_text='Konto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_invoice_lines', to='accounting.account')),
                ('tax_rate', models.ForeignKey(blank=True, help_text='Steuersatz', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoice_lines', to='accounting.taxrate')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.recurringinvoice')),
            ],
            options={
                'verbose_name': 'Vorlage für Rechnungsposition',
                'verbose_name_plural': 'Vorlagen für Rechnungspositionen',
                'ordering': ['template', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Zahlungsbetrag', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(help_text='Zahlungsdatum')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Überweisung'), ('cash', 'Barzahlung'), ('credit_card', 'Kreditkarte'), ('debit_card', 'EC-Karte'), ('paypal', 'PayPal'), ('other', 'Sonstiges')], help_text='Zahlungsart', max_length=50)),
                ('reference', models.CharField(blank=True, help_text='Referenz (z.B. Überweisungsvermerk)', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, help_text='Bankkonto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounting.account')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice')),
                ('transaction', models.OneToOneField(blank=True, help_text='Verknüpfte Buchung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='accounting.transaction')),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Name der Vorlage', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoice_templates', to=settings.AUTH_USER_MODEL)),
                ('invoice_type', models.ForeignKey(blank=True, help_text='Standard-Rechnungstyp', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_templates', to='invoices.invoicetype')),
                ('payment_term', models.ForeignKey(blank=True, help_text='Standard-Zahlungsbedingung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_templates', to='invoices.paymentterm')),
                ('receivable_account', models.ForeignKey(blank=True, help_text='Standard-Forderungskonto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_templates_as_receivable', to='accounting.account')),
                ('revenue_account', models.ForeignKey(blank=True, help_text='Standard-Ertragskonto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_templates_as_revenue', to='accounting.account')),
                ('tax_account', models.ForeignKey(blank=True, help_text='Standard-Steuerkonto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_templates_as_tax', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Rechnungsvorlage',
                'verbose_name_plural': 'Rechnungsvorlagen',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.ForeignKey(help_text='Rechnungstyp', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.invoicetype'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_term',
            field=models.ForeignKey(blank=True, help_text='Zahlungsbedingung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.paymentterm'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receivable_account',
            field=models.ForeignKey(blank=True, help_text='Forderungskonto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_as_receivable', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='revenue_account',
            field=models.ForeignKey(blank=True, help_text='Ertragskonto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_as_revenue', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(default=1, help_text='Status', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.invoicestatus'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_account',
            field=models.ForeignKey(blank=True, help_text='Steuerkonto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_as_tax', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction',
            field=models.OneToOneField(blank=True, help_text='Verknüpfte Buchung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='accounting.transaction'),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(help_text='Beschreibung')),
                ('quantity', models.DecimalField(decimal_places=4, default=1.0, help_text='Menge', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Einzelpreis', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Betrag (netto)', max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Steuerbetrag', max_digits=15)),
                ('cost_center', models.CharField(blank=True, help_text='Kostenstelle', max_length=50, null=True)),
                ('account', models.ForeignKey(blank=True, help_text='Konto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='accounting.account')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.invoice')),
                ('tax_rate', models.ForeignKey(blank=True, help_text='Steuersatz', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='accounting.taxrate')),
            ],
            options={
                'verbose_name': 'Rechnungsposition',
                'verbose_name_plural': 'Rechnungspositionen',
                'ordering': ['invoice', 'line_number'],
                'unique_together': {('invoice', 'line_number')},
            },
        ),
    ]
