# Generated by Django 4.2.11 on 2026-09-18 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0002_zugferd_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zugferdconfig',
            name='company_address',
            field=models.TextField(help_text='Firmenadresse'),
        ),
        migrations.AlterField(
            model_name='zugferdconfig',
            name='company_city',
            field=models.CharField(help_text='Stadt', max_length=100),
        ),
        migrations.AlterField(
            model_name='zugferdconfig',
            name='company_country',
            field=models.CharField(default='DE', help_text='Land', max_length=2),
        ),
        migrations.AlterField(
            model_name='zugferdconfig',
            name='company_name',
            field=models.CharField(help_text='Firmenname', max_length=200),
        ),
        migrations.AlterField(
            model_name='zugferdconfig',
            name='company_postal_code',
            field=models.CharField(help_text='Postleitzahl', max_length=20),
        ),
        migrations.AlterField(
            model_name='zugferdconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='zugferdconfig',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zugferd_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zugferdconfig',
            name='default_profile',
            field=models.ForeignKey(help_text='Standard ZUGFeRD-Profil', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_config', to='invoices.zugferdprofile'),
        ),
        migrations.AlterField(
            model_name='zugferdconfig',
            name='email_body',
            field=models.TextField(default='Anbei erhalten Sie die Rechnung {invoice_number} im ZUGFeRD-Format.', help_text='E-Mail-Text für Rechnungs-E-Mails'),
        ),
        migrations.AlterField(
            model_name='zugferdconfig',
            name='email_from',
            field=models.EmailField(help_text='Absender E-Mail', max_length=254),
        ),
        migrations.AlterField(
            model_name='zugferdconfig',
            name='email_subject',
            field=models.CharField(default='Rechnung {invoice_number}', help_text='Betreff für Rechnungs-E-Mails', max_length=200),
        ),
        migrations.AlterField(
            model_name='zugferdconfig',
            name='peppol_enabled',
            field=models.BooleanField(default=False, help_text='Peppol aktiviert'),
        ),
        migrations.AlterField(
            model_name='zugferdconfig',
            name='peppol_id',
            field=models.CharField(blank=True, help_text='Peppol-ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zugferdconfig',
            name='tax_number',
            field=models.CharField(blank=True, help_text='Steuernummer', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zugferdconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='zugferdconfig',
            name='vat_number',
            field=models.CharField(help_text='Umsatzsteuer-IdNr.', max_length=50),
        ),
        migrations.AlterField(
            model_name='zugferdinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='zugferdinvoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zugferd_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zugferdinvoice',
            name='invoice',
            field=models.OneToOneField(help_text='Verknüpfte Rechnung', on_delete=django.db.models.deletion.CASCADE, related_name='zugferd_invoice', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='zugferdinvoice',
            name='invoice_type_code',
            field=models.CharField(default='380', help_text='Rechnungstyp Code (380 = Rechnung, 381 = Gutschrift)', max_length=10),
        ),
        migrations.AlterField(
            model_name='zugferdinvoice',
            name='is_exported',
            field=models.BooleanField(default=False, help_text='Als ZUGFeRD exportiert'),
        ),
        migrations.AlterField(
            model_name='zugferdinvoice',
            name='is_imported',
            field=models.BooleanField(default=False, help_text='Aus ZUGFeRD importiert'),
        ),
        migrations.AlterField(
            model_name='zugferdinvoice',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='ZUGFeRD PDF-Datei (Hybrid)', null=True, upload_to='zugferd/pdfs/'),
        ),
        migrations.AlterField(
            model_name='zugferdinvoice',
            name='profile',
            field=models.ForeignKey(help_text='ZUGFeRD-Profil', on_delete=django.db.models.deletion.PROTECT, related_name='zugferd_invoices', to='invoices.zugferdprofile'),
        ),
        migrations.AlterField(
            model_name='zugferdinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='zugferdinvoice',
            name='xml_file',
            field=models.FileField(blank=True, help_text='ZUGFeRD XML-Datei', null=True, upload_to='zugferd/xml/'),
        ),
        migrations.AlterField(
            model_name='zugferdinvoice',
            name='zugferd_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='zugferdprofile',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='zugferdprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='zugferdprofile',
            name='max_version',
            field=models.CharField(default='2.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='zugferdprofile',
            name='min_version',
            field=models.CharField(default='2.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='zugferdprofile',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='zugferdtransmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='zugferdtransmission',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zugferd_transmissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zugferdtransmission',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Zugestellt am', null=True),
        ),
        migrations.AlterField(
            model_name='zugferdtransmission',
            name='method',
            field=models.CharField(choices=[('email', 'E-Mail'), ('peppol', 'Peppol'), ('download', 'Download'), ('api', 'API')], help_text='Übertragungsmethode', max_length=20),
        ),
        migrations.AlterField(
            model_name='zugferdtransmission',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='Empfänger E-Mail', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='zugferdtransmission',
            name='recipient_peppol_id',
            field=models.CharField(blank=True, help_text='Empfänger Peppol-ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zugferdtransmission',
            name='response_message',
            field=models.TextField(blank=True, help_text='Antwort-Nachricht'),
        ),
        migrations.AlterField(
            model_name='zugferdtransmission',
            name='response_status',
            field=models.CharField(blank=True, help_text='Antwort-Status', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zugferdtransmission',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Gesendet am', null=True),
        ),
        migrations.AlterField(
            model_name='zugferdtransmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('sent', 'Gesendet'), ('delivered', 'Zugestellt'), ('failed', 'Fehlgeschlagen'), ('received', 'Empfangen')], default='pending', help_text='Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='zugferdtransmission',
            name='transmission_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='zugferdtransmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='zugferdtransmission',
            name='zugferd_invoice',
            field=models.ForeignKey(help_text='ZUGFeRD-Rechnung', on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='invoices.zugferdinvoice'),
        ),
    ]
