# Generated by Django 4.2.11 on 2026-09-18 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('balance_sheet', 'Bilanz'), ('profit_loss', 'GuV'), ('trial_balance', 'Summen- und Saldenliste'), ('account_statement', 'Kontoauszug'), ('tax_report', 'Steuerbericht'), ('custom', 'Benutzerdefiniert')], max_length=20)),
                ('sql_query', models.TextField(blank=True, help_text='SQL-Abfrage für benutzerdefinierte Berichte')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Berichtsvorlage',
                'verbose_name_plural': 'Berichtsvorlagen',
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('report_data', models.JSONField(default=dict, help_text='Gespeicherte Berichts-Daten')),
                ('parameters', models.JSONField(default=dict, help_text='Verwendete Parameter')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_reports', to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Gespeicherter Bericht',
                'verbose_name_plural': 'Gespeicherte Berichte',
                'ordering': ['-generated_at'],
            },
        ),
    ]
