# Generated by Django 4.2.11 on 2026-09-18 11:21

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text='Kontonummer (z.B. 0600, 4000, 8000)', max_length=20, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)])),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('tax_code', models.CharField(blank=True, help_text='Steuerschlüssel', max_length=20, null=True)),
                ('cost_center', models.CharField(blank=True, help_text='Kostenstelle', max_length=50, null=True)),
                ('notes', models.TextField(blank=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Aktueller Saldo', max_digits=15)),
            ],
            options={
                'verbose_name': 'Konto',
                'verbose_name_plural': 'Konten',
                'ordering': ['account_number'],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_asset', models.BooleanField(default=False, help_text='Aktivkonto')),
                ('is_liability', models.BooleanField(default=False, help_text='Passivkonto')),
                ('is_income', models.BooleanField(default=False, help_text='Ertragskonto')),
                ('is_expense', models.BooleanField(default=False, help_text='Aufwandskonto')),
                ('balance_side', models.CharField(choices=[('debit', 'Soll'), ('credit', 'Haben')], help_text='Normal balance side for this account type', max_length=10)),
            ],
            options={
                'verbose_name': 'Kontenart',
                'verbose_name_plural': 'Kontenarten',
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kontenrahmen',
                'verbose_name_plural': 'Kontenrahmen',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Belegart',
                'verbose_name_plural': 'Belegarten',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('journal_type', models.CharField(choices=[('general', 'Hauptbuch'), ('sales', 'Verkaufsjournal'), ('purchase', 'Einkaufsjournal'), ('bank', 'Bankjournal'), ('cash', 'Kassajournal')], max_length=20)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journale',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('period_type', models.CharField(choices=[('month', 'Monat'), ('quarter', 'Quartal'), ('year', 'Jahr')], max_length=20)),
                ('fiscal_year', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Periode',
                'verbose_name_plural': 'Perioden',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reconciled_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='accounting.account')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abstimmung',
                'verbose_name_plural': 'Abstimmungen',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('tax_type', models.CharField(choices=[('vat', 'Umsatzsteuer'), ('input_vat', 'Vorsteuer'), ('other', 'Sonstige')], max_length=20)),
            ],
            options={
                'verbose_name': 'Steuersatz',
                'verbose_name_plural': 'Steuersätze',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_number', models.CharField(help_text='Belegnummer', max_length=50, unique=True)),
                ('date', models.DateField(help_text='Buchungsdatum')),
                ('posting_date', models.DateField(blank=True, help_text='Wertstellungsdatum', null=True)),
                ('description', models.TextField(help_text='Buchungstext')),
                ('reference', models.CharField(blank=True, help_text='Referenz (z.B. Rechnungsnummer)', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_posted', models.BooleanField(default=False, help_text='Gebucht (nicht mehr änderbar)')),
                ('is_reversed', models.BooleanField(default=False, help_text='Storniert')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounting.documenttype')),
                ('reversal_reference', models.ForeignKey(blank=True, help_text='Referenz zur Stornobuchung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='accounting.transaction')),
            ],
            options={
                'verbose_name': 'Buchung',
                'verbose_name_plural': 'Buchungen',
                'ordering': ['-date', '-document_number'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_line', models.CharField(blank=True, max_length=200)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.reconciliation')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_items', to='accounting.transaction')),
            ],
            options={
                'verbose_name': 'Abstimmungsposition',
                'verbose_name_plural': 'Abstimmungsposten',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.journal')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='accounting.transaction')),
            ],
            options={
                'verbose_name': 'Journaleintrag',
                'verbose_name_plural': 'Journaleinträge',
                'ordering': ['journal', '-date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='ClosingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_closing_entries', to=settings.AUTH_USER_MODEL)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closing_entries_from', to='accounting.account')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closing_entries', to='accounting.period')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closing_entries_to', to='accounting.account')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closing_entry', to='accounting.transaction')),
            ],
            options={
                'verbose_name': 'Abschlussbuchung',
                'verbose_name_plural': 'Abschlussbuchungen',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accounttype'),
        ),
        migrations.AddField(
            model_name='account',
            name='chart_of_accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, help_text='Übergeordnetes Konto für Hierarchie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='accounting.account'),
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('debit', 'Soll'), ('credit', 'Haben')], help_text='Buchungsseite', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Betrag', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Steuerbetrag', max_digits=15)),
                ('description', models.TextField(blank=True, help_text='Buchungstext für diese Position')),
                ('cost_center', models.CharField(blank=True, help_text='Kostenstelle', max_length=50, null=True)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_lines', to='accounting.account')),
                ('tax_rate', models.ForeignKey(blank=True, help_text='Steuersatz', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_lines', to='accounting.taxrate')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.transaction')),
            ],
            options={
                'verbose_name': 'Buchungsposition',
                'verbose_name_plural': 'Buchungspositionen',
                'ordering': ['transaction', 'line_number'],
                'unique_together': {('transaction', 'line_number')},
            },
        ),
    ]
